remove unsed parts

diff --git a/scripts/zet b/scripts/zet
--- a/scripts/zet
+++ b/scripts/zet
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/bin/bash
 set -e
 
 # This zet script is a multicall executable, which means you may have
@@ -32,7 +32,8 @@ DIR="$ZETDIR/$EXE"
 
 # ------------------------- complete context -------------------------
 
-declare -a COMMANDS=(usage a add q query text d dir e edit id urlencode titles last title body before after ids v video for)
+#declare -a COMMANDS=(usage a add q query text d dir e edit id urlencode titles last title body before after ids v video for)
+declare -a COMMANDS=(usage a add q query text d dir e edit id urlencode titles last title body before after ids)
 
 if [[ -n $COMP_LINE ]]; then
     for c in "${COMMANDS[@]}"; do
@@ -48,44 +49,44 @@ _usage() {
     printf "usage: ${0##*/} (${cmds// /|})\n"
 }
 
-_set_video() {
-  local dir="$(_d)/$1"
-  local readme="$dir/README.md"
-  [[ ! -r $readme ]] && echo "<not found>" && return 1
-  if [[ $(sed '3q;d' "$readme") =~ ^📺 ]]; then
-    echo -e "3c\n📺 <$2>\n.\nwq" | ed "$readme" >/dev/null
-  else
-    echo -e "2a\n📺 <$2>\n\n.\nwq" | ed "$readme" >/dev/null
-  fi
-}
-
-_video() {
-  local zet="$1"
-  local vid="$2"
-  if [[ -n "$vid" ]]; then
-    _set_video "$@"
-    return $?
-  fi
-  local IFS=$'\n'
-  if [[ -z $zet ]]; then
-    while read -r line; do
-      _video $line
-    done
-    return 0
-  fi
-  local dir="$(_d)/$1"
-  local readme="$dir/README.md"
-  [[ ! -r $readme ]] && echo "<not found>" && return 1
-  while read -r line; do
-    if [[ $line =~ ^📺\ \<(.*)\> ]]; then
-      echo "${BASH_REMATCH[1]}"
-      return 0
-    fi
-  done < "$readme"
-  return 1
-}
-
-_v() { _video "$@"; }
+#_set_video() {
+#  local dir="$(_d)/$1"
+#  local readme="$dir/README.md"
+#  [[ ! -r $readme ]] && echo "<not found>" && return 1
+#  if [[ $(sed '3q;d' "$readme") =~ ^📺 ]]; then
+#    echo -e "3c\n📺 <$2>\n.\nwq" | ed "$readme" >/dev/null
+#  else
+#    echo -e "2a\n📺 <$2>\n\n.\nwq" | ed "$readme" >/dev/null
+#  fi
+#}
+#
+#_video() {
+#  local zet="$1"
+#  local vid="$2"
+#  if [[ -n "$vid" ]]; then
+#    _set_video "$@"
+#    return $?
+#  fi
+#  local IFS=$'\n'
+#  if [[ -z $zet ]]; then
+#    while read -r line; do
+#      _video $line
+#    done
+#    return 0
+#  fi
+#  local dir="$(_d)/$1"
+#  local readme="$dir/README.md"
+#  [[ ! -r $readme ]] && echo "<not found>" && return 1
+#  while read -r line; do
+#    if [[ $line =~ ^📺\ \<(.*)\> ]]; then
+#      echo "${BASH_REMATCH[1]}"
+#      return 0
+#    fi
+#  done < "$readme"
+#  return 1
+#}
+#
+#_v() { _video "$@"; }
 
 _urlencode() {
   local string="$*"
@@ -165,7 +166,7 @@ _titles() {
 
 _last() {
   local line=$(_titles | tail -1)
-  echo "* [${line#* }](https://github.com/rwxrob/zet/tree/main/${line%% *})"
+  echo "* [${line#* }](https://github.com/mrbooshehri/zet/tree/main/${line%% *})"
 }
 
 _text() {
@@ -202,9 +203,9 @@ _query() {
   term="$*"
   it="https://github.com/$GITUSER/$EXE/search?q=$(_urlencode $term)"
   echo "[$term]: <$it>"
-  local chat=$(command -v chat)
-  [[ -z $chat ]] && return 0
-  exec chat "$it"
+#  local chat=$(command -v chat)
+#  [[ -z $chat ]] && return 0
+#  exec chat "$it"
 }
 _q() { _query "$@"; }
 
@@ -224,13 +225,13 @@ _before() {
   echo $prev
 }
 
-_for() {
-  local mkv="$1"
-  [[ $mkv =~ - ]] && mkv=$(mkv2isosec "$1")
-  local id=${mkv##*/}
-  id=${id%.mkv}
-  zet before $id
-}
+#_for() {
+#  local mkv="$1"
+#  [[ $mkv =~ - ]] && mkv=$(mkv2isosec "$1")
+#  local id=${mkv##*/}
+#  id=${id%.mkv}
+#  zet before $id
+#}
 
 _after() {
   local id=$1
